# Generated by Django 5.2 on 2025-04-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimeraApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.TextField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
