# Generated by Django 5.2 on 2025-04-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción del producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('available', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Foto del producto')),
            ],
        ),
    ]
