# Generated by Django 5.2 on 2025-04-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0003_alter_car_name_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='title',
            field=models.CharField(default='Sin título', max_length=100),
        ),
    ]
