# Generated by Django 5.2 on 2025-04-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0004_remove_car_name_car_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
